version: "2"
services:
  redis:
    container_name: redis
    image: redis:latest

  db:
    container_name: db
    image: postgres:latest
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pguser
      POSTGRES_DB: debateit

  web:
    container_name: web
    build: .
    volumes:
      - .:/app
    environment:
     - FLASK_DEBUG=1
    ports:
     - "80:5000"
    depends_on:
      - redis
      - db

  test:
    container_name: test
    build: .
    links:
      - web
    depends_on:
      - web
    volumes:
    - .:/app
    command: "python -m unittest discover"