version: "2"
services:
  redis:
    image: redis:latest

  db:
    image: postgres:latest
    volumes:
      - /private/var/lib/postgresql:/var/lib/postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pguser
      POSTGRES_DB: pgdb

  web:
    build: .
    volumes:
      - .:/app
    environment:
     - FLASK_DEBUG=1
    ports:
     - "5000:5000"
    depends_on:
      - redis
      - db
