version: "3"
services:
  redis:
    image: redis:latest

  web:
    build: .
    volumes:
      - .:/app
    environment:
     - FLASK_DEBUG=1
    ports:
     - "5000:5000"
    depends_on:
      - redis
