"""Added description to debate

Revision ID: 351ab6563a24
Revises: 
Create Date: 2018-10-16 15:08:05.726914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '351ab6563a24'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('debate', sa.Column('description', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('debate', 'description')
    # ### end Alembic commands ###
